import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowRight, Activity, Shield, BrainCircuit } from "lucide-react"

export default function Home() {
    return (
        <div className="flex flex-col min-h-screen">
            <header className="px-6 lg:px-10 h-16 flex items-center border-b">
                <Link href="#" className="flex items-center justify-center gap-2">
                    <Activity className="h-6 w-6 text-primary" />
                    <span className="font-bold text-xl">Computer Spy AI</span>
                </Link>
                <nav className="ml-auto flex gap-4 sm:gap-6">
                    <Link href="/dashboard/activity" className="text-sm font-medium hover:underline underline-offset-4 flex items-center">
                        Dashboard
                    </Link>
                </nav>
            </header>
            <main className="flex-1">
                <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 flex flex-col items-center text-center px-4">
                    <div className="container px-4 md:px-6">
                        <div className="flex flex-col items-center space-y-4 text-center">
                            <div className="space-y-2">
                                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                                    Unlock Your Workflow Potential
                                </h1>
                                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                                    AI-powered activity tracking that respects your privacy while finding efficiency bottlenecks.
                                </p>
                            </div>
                            <div className="space-x-4">
                                <Link href="/dashboard/activity">
                                    <Button size="lg" className="h-12 px-8">
                                        Go to Dashboard <ArrowRight className="ml-2 h-4 w-4" />
                                    </Button>
                                </Link>
                                <Link href="https://github.com/chaimgelber23/computer-spy-ai" target="_blank">
                                    <Button variant="outline" size="lg" className="h-12 px-8">
                                        View on GitHub
                                    </Button>
                                </Link>
                            </div>
                        </div>
                    </div>
                </section>

                <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-50 dark:bg-gray-900 flex justify-center">
                    <div className="container px-4 md:px-6 grid gap-10 sm:grid-cols-2 lg:grid-cols-3">
                        <div className="flex flex-col items-center space-y-4 text-center">
                            <div className="p-4 bg-white dark:bg-gray-800 rounded-full shadow-sm">
                                <Activity className="h-8 w-8 text-blue-500" />
                            </div>
                            <h2 className="text-xl font-bold">Smart Tracking</h2>
                            <p className="text-gray-500 dark:text-gray-400">
                                Automatically logs active windows and detects idle time. No manual timers needed.
                            </p>
                        </div>
                        <div className="flex flex-col items-center space-y-4 text-center">
                            <div className="p-4 bg-white dark:bg-gray-800 rounded-full shadow-sm">
                                <BrainCircuit className="h-8 w-8 text-purple-500" />
                            </div>
                            <h2 className="text-xl font-bold">AI Insights</h2>
                            <p className="text-gray-500 dark:text-gray-400">
                                Get weekly reports on repetitive tasks and efficiency scores generated by GenAI.
                            </p>
                        </div>
                        <div className="flex flex-col items-center space-y-4 text-center">
                            <div className="p-4 bg-white dark:bg-gray-800 rounded-full shadow-sm">
                                <Shield className="h-8 w-8 text-green-500" />
                            </div>
                            <h2 className="text-xl font-bold">Private & Secure</h2>
                            <p className="text-gray-500 dark:text-gray-400">
                                Your data stays yours. Designed for personal productivity, not corporate surveillance.
                            </p>
                        </div>
                    </div>
                </section>
            </main>
            <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
                <p className="text-xs text-gray-500 dark:text-gray-400">© 2026 Computer Spy AI. All rights reserved.</p>
                <nav className="sm:ml-auto flex gap-4 sm:gap-6">
                    <Link className="text-xs hover:underline underline-offset-4" href="#">
                        Terms of Service
                    </Link>
                    <Link className="text-xs hover:underline underline-offset-4" href="#">
                        Privacy
                    </Link>
                </nav>
            </footer>
        </div>
    )
}
